spring:
  mvc:
    async:
      request-timeout: -1

client:
  llmQaNumber: 5
  iat:
    server: xun_fei
    appid: b15bda99
    appSecret: NzM2ZGZjYjhkZGI5OWExMmQ3NjUzYzJi
    apiKey: 8b4820ef357795b55b9add06c879f2e1
    vadEos: 30000
  tts:
    server: volcengine
    appid: 2406304386
    accessToken: xxQRz09WulY5Ft36ROCP0VcCprFWUnhh
    rate: 24000
    voiceType: BV051_streaming
    speedRatio: 1.3
  llm:
    server: dashscope
    apiKey: sk-34551a31745c401da195322fad4e7728
    llm: qwen-max
  llm_init_messages: 你是一个语音助手....
  cacheTTSNumber: 1000